# Generated by Django 3.1.2 on 2021-08-13 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('change_at', models.DateTimeField(auto_now=True)),
                ('creator_ip', models.GenericIPAddressField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClipBoardContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('change_at', models.DateTimeField(auto_now=True)),
                ('publish_ip', models.GenericIPAddressField()),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.channel')),
            ],
        ),
    ]
