# Generated by Django 3.1.2 on 2021-07-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210717_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='creator_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
